### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by MrHackrer** [respecting/shortlink-bot#4]
im facing difficulty it placing th bot token i have done exactly told in the  read me

**Comment by lem6ns** [comment]
You formatted your .env file like this:
```
token=bottoken
prefix=prefix
``` 
changing the values accordingly. And you have not named it
`config.env`, `.env.txt`, or anything like that. If you did one of those things wrong, that's why it's not working.

**Comment by MrHackrer** [comment]
done exactly like this still error

**Comment by MrHackrer** [comment]
done thx
