### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrHackrer** [respecting/shortlink-bot#7]
it says the link is invalid

**Comment by lem6ns** [comment]
Debug the error by logging it.

**Comment by Raghav20-noob** [comment]
i am nuked

**Comment by lem6ns** [comment]
> 
> 
> i am nuked

so much people are saying that I nuked it, but I didn't. it wasn't even my bot that i invited??? (shortlink bot)
from the information i gathered, it was someone elses bot AND people are "justifying" it by saying it was my source code, EVEN THOUGH THERE'S NO CODE TO DELETE CHANNELS.
